site_name: DocGen

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
  - API Reference:
      - MergeData API: api/mergedata.md
      - HTML Merge API: api/htmlmerge.md

docs_dir: docs/src
site_dir: docs/site
theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - django
    - bash

markdown_extensions:
  - toc:
      permalink: true
      title: "Contents"
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mkdocs-click

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_if_no_docstring: true
